import { useState } from "react";
import { ArrowDown, Braces, Check, CheckCheck, CircleDashed, Clock3, Code2, Copy, GitBranch, Globe2, Info, Loader2, Route, ScanLine, ShieldCheck, Waypoints } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { type RoutingTrace } from "@/api/client";
import { cn } from "@/lib/utils";

export function SupervisorTrace({ trace, busy = false, example = false }: { trace?: RoutingTrace; busy?: boolean; example?: boolean }) {
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const selected = trace?.selected?.[0];
  const slots = trace?.slots ?? trace?.extracted_slots ?? {};
  const timing = Object.entries(trace?.latency_ms ?? {}).filter((entry) => typeof entry[1] === "number");
  const total = timing.reduce((sum, [, value]) => sum + value, 0);
  const language = trace?.language === "ru" ? "Russian" : trace?.language === "kk" || trace?.language === "kz" ? "Kazakh" : trace?.language;
  async function copy() { try { await navigator.clipboard.writeText(JSON.stringify(trace, null, 2)); setCopied(true); setCopyError(false); setTimeout(() => setCopied(false), 2000); } catch { setCopyError(true); } }
  return <Card className="panel-shadow gap-0 overflow-hidden py-0">
    <div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl border bg-[#f8f9f4]"><Waypoints size={17}/></span><div><h2 className="text-[13px] font-semibold">Behind the conversation</h2><p className="mt-0.5 text-[10px] text-muted-foreground">A little transparency, at every step</p></div></div><Badge variant="outline" className="gap-1.5 rounded-md text-[9px] font-normal">{busy ? <Loader2 size={10} className="animate-spin"/> : <span className={cn("size-1.5 rounded-full", trace ? "bg-[#80a463]" : "bg-[#c1c8b8]")}/>} {busy ? "Routing" : example ? "Example" : trace ? "Updated" : "Listening"}</Badge></div>
    <Tabs defaultValue="decision" className="gap-0"><div className="border-b px-5 pt-3"><TabsList className="h-9 w-full justify-start gap-5 rounded-none bg-transparent p-0"><TabsTrigger value="decision" className="h-9 flex-none rounded-none border-0 border-b-2 border-transparent bg-transparent px-0 pb-3 text-[11px] font-normal shadow-none data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:shadow-none"><Route size={13}/>Routing decision</TabsTrigger><TabsTrigger value="details" className="h-9 flex-none rounded-none border-0 border-b-2 border-transparent bg-transparent px-0 pb-3 text-[11px] font-normal shadow-none data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:shadow-none"><Braces size={13}/>Details</TabsTrigger><TabsTrigger value="raw" className="ml-auto h-9 flex-none rounded-none border-0 border-b-2 border-transparent bg-transparent px-0 pb-3 text-[11px] font-normal shadow-none data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:shadow-none"><Code2 size={13}/>JSON</TabsTrigger></TabsList></div>
    <TabsContent value="decision" className="m-0 px-5 pb-5 pt-5">
      <div className="mb-4 flex items-center justify-between"><p className="text-[9px] font-semibold tracking-[1.3px] text-[#909982]">THE ROUTING JOURNEY</p><span className="text-[9px] text-muted-foreground">{trace ? `Turn ${trace.turn_id ?? "—"}` : "Waiting for a message"}</span></div>
      <div className="dot-grid rounded-xl border bg-[#fafbf7] px-4 py-5">
        <JourneyStep icon={Globe2} title="Understand the message" description={trace ? `${language ?? "Unknown"} detected · text input` : "Detect language & understand context"} active={!!trace}/>
        <div className="flex justify-center py-1.5"><ArrowDown size={14} className="text-[#bac5b0]"/></div>
        <JourneyStep icon={GitBranch} title="Find the right path" description={selected ? `${selected.id} · ${selected.confidence ?? "unrated"} confidence` : "Match intent to an insurance scenario"} active={!!selected} highlighted/>
        <div className="flex justify-center py-1.5"><ArrowDown size={14} className="text-[#bac5b0]"/></div>
        <JourneyStep icon={ShieldCheck} title="Respond with confidence" description={trace ? trace.fallback?.active ? "Fallback · clarification needed" : trace.execution?.status?.replace(/_/g, " ") ?? "Response ready" : "Clarify, answer, or connect to a specialist"} active={!!trace}/>
      </div>
      {trace ? <div className="mt-5 space-y-4"><div className="flex items-center justify-between"><h3 className="text-[11px] font-semibold">Selected scenario</h3><Badge variant="secondary" className="text-[9px] capitalize">{selected?.confidence ?? "Unknown"} confidence</Badge></div><div className="rounded-lg border bg-[#fcfdf9] p-3"><p className="break-words text-xs font-medium">{selected?.id ?? "No scenario selected"}</p><p className="mt-1.5 text-[11px] leading-5 text-muted-foreground">{selected?.reason ?? "No explanation provided."}</p></div>{trace.clarification?.required && <div className="rounded-lg bg-amber-50 p-3 text-[11px] leading-5 text-amber-800"><span className="font-semibold">Clarification needed</span><p>{trace.clarification.question ?? "More details are needed to continue."}</p></div>}{trace.fallback?.active && <p className="rounded-lg bg-amber-50 p-3 text-[11px] text-amber-800">The router used a fallback. Check the details for more information.</p>}<div className="flex items-center justify-between border-t pt-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><Clock3 size={12}/>Processing time</span><span className="font-mono">{timing.length ? `${Math.round(total)} ms` : "Not reported"}</span></div></div> : <><div className="mb-4 mt-5 flex items-center gap-2 text-[11px] font-semibold"><ScanLine size={14} className="text-[#91a47b]"/>Ready to connect the dots</div><p className="text-[11px] leading-6 text-muted-foreground">Send a message to see the selected scenario, confidence, and reasoning appear here in real time.</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-lg border border-dashed p-3"><p className="text-[9px] text-muted-foreground">DETECTED LANGUAGE</p><p className="mt-2 text-xs text-[#b1b8a7]">Awaiting input</p></div><div className="rounded-lg border border-dashed p-3"><p className="text-[9px] text-muted-foreground">ROUTING CONFIDENCE</p><p className="mt-2 text-xs text-[#b1b8a7]">Awaiting input</p></div></div></>}
    </TabsContent>
    <TabsContent value="details" className="m-0 space-y-5 p-5">{trace ? <><Detail title="Extracted details" value={slots}/><Detail title="Alternative scenarios" value={trace.alternatives ?? []}/><Detail title="Execution" value={trace.execution}/><Detail title="Clarification" value={trace.clarification}/>{trace.fallback && <Detail title="Fallback" value={trace.fallback}/>} {!!trace.handoff && <Detail title="Handoff" value={trace.handoff}/>}<Detail title="Timing (ms)" value={trace.latency_ms}/><Detail title="Metadata" value={trace.metadata}/></> : <EmptyDetails/>}</TabsContent>
    <TabsContent value="raw" className="m-0 p-5">{trace ? <><div className="mb-3 flex items-center justify-between"><p className="text-[11px] font-medium">Routing trace</p><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={copy}>{copied ? <CheckCheck size={12}/> : <Copy size={12}/>} {copied ? "Copied" : "Copy JSON"}</Button></div>{copyError && <p role="alert" className="mb-2 text-xs text-destructive">Clipboard unavailable. Select and copy the JSON below.</p>}<pre className="max-h-[430px] overflow-auto rounded-xl bg-[#f0f3eb] p-4 text-[10px] leading-5">{JSON.stringify(trace, null, 2)}</pre></> : <EmptyDetails/>}</TabsContent>
    </Tabs>
    <div className="flex items-start gap-2 border-t bg-[#fafbf6] px-5 py-3.5"><Info size={12} className="mt-0.5 shrink-0 text-[#95a181]"/><p className="text-[10px] leading-5 text-[#8a967b]">{example ? "Illustrative data. Start a new session to see live routing results." : "Every decision leaves a trace. Nothing gets lost between the question and the answer."}</p></div>
  </Card>;
}
function JourneyStep({ icon: Icon, title, description, active, highlighted }: { icon: typeof Globe2; title: string; description: string; active: boolean; highlighted?: boolean }) {
  return <div className={cn("flex items-center gap-3 rounded-lg border bg-white px-3 py-3", highlighted && "border-[#cfddbb] bg-[#f3f7eb]")}><span className={cn("flex size-8 shrink-0 items-center justify-center rounded-lg bg-[#f1f3ec] text-[#8d9b7b]", highlighted && "bg-[#e4edcf] text-[#71924e]")}><Icon size={15}/></span><div className="min-w-0 flex-1"><h3 className="text-[11px] font-medium">{title}</h3><p className="mt-1 break-words text-[9px] leading-4 text-muted-foreground">{description}</p></div>{active ? <Check size={13} className="shrink-0 text-primary"/> : <CircleDashed size={13} className="shrink-0 text-[#c1c9b6]"/>}</div>;
}
function Detail({ title, value }: { title: string; value: unknown }) { return <section><h3 className="mb-2 text-[11px] font-semibold">{title}</h3><pre className="overflow-auto rounded-lg bg-muted p-3 text-[10px] leading-5">{value && Object.keys(Object(value)).length ? JSON.stringify(value, null, 2) : "None reported"}</pre></section>; }
function EmptyDetails() { return <div className="py-20 text-center"><Braces className="mx-auto mb-4 text-[#9ba98b]"/><p className="text-xs text-muted-foreground">Your next message will tell a story.</p><p className="mt-2 text-[10px] text-muted-foreground">Routing details will appear here.</p></div>; }
